steps:
- name: 'gcr.io/cloud-builders/gcloud:latest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "BOT_TOKEN=$$BOT_TOKEN" > .env
    echo "GUILD_ID=$$GUILD_ID" >> .env
    echo "CLIENT_ID=$$CLIENT_ID" >> .env
    echo "PROJECT_ID=$$PROJECT_ID" >> .env
    echo "LOCATION=$$LOCATION" >> .env
    echo "MODEL=$$MODEL" >> .env
    cat .env # Optional: Print the contents of .env to the build logs
  secretEnv: ['BOT_TOKEN', 'GUILD_ID', 'CLIENT_ID', 'PROJECT_ID', 'LOCATION', 'MODEL']

- name: node:20
  entrypoint: npm
  args: ["install"]

- name: node:20
  entrypoint: node
  args: ["main.js"]
  
availableSecrets:
  secretManager:
  - versionName: "projects/$PROJECT_ID/secrets/discord-bot-token/versions/latest"
    env: "BOT_TOKEN"
  - versionName: "projects/$PROJECT_ID/secrets/guild-id/versions/latest"
    env: "GUILD_ID"
  - versionName: "projects/$PROJECT_ID/secrets/client-id/versions/latest"
    env: "CLIENT_ID"
  - versionName: "projects/$PROJECT_ID/secrets/project-id/versions/latest"
    env: "PROJECT_ID"
  - versionName: "projects/$PROJECT_ID/secrets/location/versions/latest"
    env: "LOCATION"
  - versionName: "projects/$PROJECT_ID/secrets/model/versions/latest"
    env: "MODEL"
    
options:
  logging: CLOUD_LOGGING_ONLY 