version: '2.1'

stages:
- stage: build
  jobs:
  - job: build_job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x' 
      displayName: 'Install Node.js'

    - script: |
        npm install
        node main.js
      displayName: 'Run main.js'